### PR TITLE
Begin anew

### PR DESCRIPTION
**Pull request by itslevir**
Hey Daniel. Not sure if you see this but after taking a second look at the the codebase, this shit is completely fucked. Not only to Sam's fault, but also my own. I honestly suggest resetting the frontend at least. This PR unfucks almost everything. Whether you want to keep it is up to you.

Discussion is welcomed

### CODE REVIEW

**Comment by dkravec** [comment]
i think some stuff could stay, but yea most of the code can be redone
but of course with that it could/will be a longer time before its up again

i think ill accept the pr in a bit, then maybe bring some stuff back in, or just do a really basic splash+login+home screen maybe

**Comment by itslevir** [comment]
just pushed a few extra commits with some really basic starting points. feel free to edit from here

**Comment by itslevir** [comment]
hey, thinking about this project. for the sake of consistency, I would personally create a secondary repository with branding styles, and more importantly (svelte) design components that can be used for this repo. a private library of sorts before moving any further with UI and design, similar to what i did a few years ago in [@/foundation-ui](https://github.com/Huelet/foundation-ui)

**Comment by dkravec** [comment]
question- (sorry this went into a tangent, and I kept writing)

wouldn't just restarting be easier, rather than undoing some stuff and then redoing it
or just deleting the stuff that doesn't work and keeping the main parts


currently the main repo "works", I can login (with interact due to updates I did on the backend), videos don't work but I need to redo it anyways

its probably easier to clean up the code than to rewrite the entire thing, I don't have the time to remake the entire thing and also work on (and possibly redo) interact's code. I also need to keep track of the differences of the 2 codebases taking wildly different approaches


maybe there can be a branch specially for this, that can be updated (if you want) until it is replace the main branch. but I could keep updating the main branch and clean it up

it also looks like you are adding oauth for 3rd party apps, which ig is cool we could do that, but seems overly complicated for now, main prioierty should probably be getting videos working, which ill work on because I want to get it running on minio and get everything self-hosted instead of using railway or azure



I do like the secondary repo for styles, and the cleaning of code which we can implement 

(back the the start), restarting may be easier, starting from nothing installing packages, and ill be able to keep it minimal and know what I want.

idk. lmk what you think, either the 2nd branch for this until its featurematch and working with the backend well, or restarting from 0 may be best

**Comment by dkravec** [comment]
maybe just restarting is best, I had it running, and then I wanted to update the packages (I saw you had as well) and now its not running, interlinking dependancies or whatever

maybe ill build it again to be similar to interact's codebase (at least for the backend), frontend, idk just a lot less dependancies

the main thing I like about interact's codebase is how few dependancies it has, and its really easy to start up

**Comment by itslevir** [comment]
sorry for the late reply. can you elaborate on what you mean by turning it more like interact?

**Pull request closed without merging**
